config:
  credentials: []
  project_repos:
    github.com/3dbionotes-community/3DBIONOTES:
      branch: master
      repo: https://github.com/3dbionotes-community/3DBIONOTES
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/3dbionotes-community/3DBIONOTES git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-smalt-camel.sh
        container: qc.acc_lumpy-dandelion-caiman
  QC.Doc:
    repos:
      github.com/3dbionotes-community/3DBIONOTES find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-buff-hare.sh
        container: qc.doc_beady-corn-heron
      github.com/3dbionotes-community/3DBIONOTES git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-ultramarine-mouse.sh
        container: qc.doc_sunny-myrtle-sheepdog
      github.com/3dbionotes-community/3DBIONOTES markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-crimson-stoat.sh
        container: qc.doc_foggy-amethyst-zonkey
  QC.Lic:
    repos:
      github.com/3dbionotes-community/3DBIONOTES licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-purple-bird.sh
        container: qc.lic_geeky-blue-tuatara
  QC.Ver:
    repos:
      github.com/3dbionotes-community/3DBIONOTES get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-gold-lizard.sh
        container: qc.ver_whiny-myrtle-bison
timeout: 1800
