config:
  credentials: []
  project_repos:
    github.com/3dbionotes-community/3DBIONOTES:
      branch: DEV-quality-software-assessment
      repo: https://github.com/3dbionotes-community/3DBIONOTES
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/3dbionotes-community/3DBIONOTES git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-firebrick-magpie.sh
        container: qc.acc_ugly-violet-zebra
  QC.Doc:
    repos:
      github.com/3dbionotes-community/3DBIONOTES find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-denim-devil.sh
        container: qc.doc_squirrely-zucchini-indri
      github.com/3dbionotes-community/3DBIONOTES git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-jade-salamander.sh
        container: qc.doc_baggy-cyan-mastiff
      github.com/3dbionotes-community/3DBIONOTES markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-aquamarine-macaque.sh
        container: qc.doc_cheeky-aquamarine-impala
  QC.Lic:
    repos:
      github.com/3dbionotes-community/3DBIONOTES licensee:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-auburn-balinese.sh
        container: qc.lic_woolly-cream-havanese
  QC.Sty:
    repos:
      github.com/3dbionotes-community/3DBIONOTES jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-xanthic-yak.sh
        container: qc.sty_lumpy-crimson-vole
      github.com/3dbionotes-community/3DBIONOTES rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-chocolate-cichlid.sh
        container: qc.sty_skinny-apricot-zonkey
      github.com/3dbionotes-community/3DBIONOTES stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-seashell-ibis.sh
        container: qc.sty_sunny-turquoise-dane
  QC.Ver:
    repos:
      github.com/3dbionotes-community/3DBIONOTES get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cornflower-coati.sh
        container: qc.ver_cozy-tomato-dachsbracke
timeout: 1800
