config:
  credentials: []
  project_repos:
    github.com/3dbionotes-community/3DBIONOTES:
      branch: master
      repo: https://github.com/3dbionotes-community/3DBIONOTES
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/3dbionotes-community/3DBIONOTES git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-black-zebra.sh
        container: qc.acc_lovely-lime-macaw
  QC.Doc:
    repos:
      github.com/3dbionotes-community/3DBIONOTES find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-russet-schnauzer.sh
        container: qc.doc_frumpy-white-duck
      github.com/3dbionotes-community/3DBIONOTES git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-plum-lemur.sh
        container: qc.doc_trippy-seashell-cuttlefish
      github.com/3dbionotes-community/3DBIONOTES markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-wisteria-mandrill.sh
        container: qc.doc_squirrely-rust-eagle
  QC.Lic:
    repos:
      github.com/3dbionotes-community/3DBIONOTES licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-magenta-macaw.sh
        container: qc.lic_sunny-burgundy-cheetah
  QC.Sty:
    repos:
      github.com/3dbionotes-community/3DBIONOTES jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-periwinkle-axolotl.sh
        container: qc.sty_flabby-tomato-russel
      github.com/3dbionotes-community/3DBIONOTES rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-smalt-forest.sh
        container: qc.sty_droopy-dandelion-lemur
      github.com/3dbionotes-community/3DBIONOTES stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-rose-impala.sh
        container: qc.sty_lovely-sangria-tang
  QC.Ver:
    repos:
      github.com/3dbionotes-community/3DBIONOTES get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-alizarin-dragonfly.sh
        container: qc.ver_hasty-scarlet-emu
timeout: 1800
